server:
  port: 8090
spring:
  kafka:
    consumer:
      topic: voting-topic
      groupId: voting-api-v1
      bootstrap-server: 127.0.0.1:9092
      enable-auto-commit: false
      auto-offset-reset: earliest
      schemaRegistryUrl: "http://127.0.0.1:8081"
      specific-avro-reader: true

    producer:
      groupId: voting-api-v1
      topic: voting-topic
      bootstrap-server: 127.0.0.1:9092
      acksConfig: all
      retriesConfig: 10
      schemaRegistryUrl: "http://127.0.0.1:8081"
